typography_spectrum: 0.08218616852536798
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8075244277715683
  lightness: 0.6600155713967979
  saturation: 0.47206643084064126
  rhythmicContrast: 0.15755240619182587
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.22322780801914632
analytics:
  google: null
  facebook: null
  twitter: null
author:
  url: www.zukunvt.com
  email: vm@zukunvt.com
  name: Viktor it its
name: zukunvt
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'viktor '
    url: viktormatic.com
    type: external
favicon: null
title: the place to be
purpose: []
