name: zukunvt
favicon: null
layout_spectrum: 0.22322780801914632
typography_spectrum: 0.08218616852536798
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8075244277715683
  lightness: 0.6600155713967979
  saturation: 0.47206643084064126
  rhythmicContrast: 0.15755240619182587
purpose: []
